import PDFDocument from "pdfkit";
import archiver from "archiver";
import { Readable, PassThrough } from "stream";

function pdfBufferFromDoc(build) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "A4" });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    try {
      build(doc);
      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

/** One multi-section PDF: letter summary, application summary, receipts */
export async function buildAdmissionPdf(institute, student, university) {
  const s = typeof student.toJSON === "function" ? student.toJSON() : student;
  const u = university;
  return pdfBufferFromDoc((doc) => {
    doc.fontSize(16).fillColor("#1a365d").text(institute.name || "Institute", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#64748b").text("Admission document pack", { align: "center" });
    doc.moveDown(1.2);

    doc.fontSize(12).fillColor("#1a365d").text("1. Letter of admission (summary)", { underline: true });
    doc.moveDown(0.4);
    doc.fontSize(10).fillColor("#111").text(`Ref: ${s.admission_no}    Date: ${s.admission_date || "—"}`);
    doc.text(`Student: ${s.full_name}`);
    doc.text(`Course: ${s.course_name || "B.Ed"}   Year: ${s.academic_year || "—"}`);
    if (u?.name) doc.text(`University (placement): ${u.name}`);
    doc.text(
      `Fee: ${s.course_fee_amount != null ? `₹${Number(s.course_fee_amount).toLocaleString("en-IN")}` : "—"}   Paid: ${s.amount_paid != null ? `₹${Number(s.amount_paid).toLocaleString("en-IN")}` : "—"}`
    );
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#1a365d").text("2. Application details", { underline: true });
    doc.moveDown(0.4);
    doc.fontSize(10).fillColor("#111");
    doc.text(`Father: ${s.father_name || "—"}   Mother: ${s.mother_name || "—"}`);
    doc.text(`Phone: ${s.phone || "—"}   Address: ${(s.address || "—").slice(0, 500)}`);
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#1a365d").text("3. Fee receipts (audit trail)", { underline: true });
    doc.moveDown(0.4);
    const receipts = Array.isArray(s.payment_receipts) ? s.payment_receipts : [];
    if (receipts.length === 0) {
      doc.fontSize(10).text("No receipt entries yet — amounts recorded without receipt rows.");
    } else {
      receipts.forEach((r, i) => {
        doc.fontSize(10).text(
          `${i + 1}. ${r.receipt_no} — ₹${Number(r.amount).toLocaleString("en-IN")} — ${r.recorded_at || "—"}`
        );
      });
    }
    doc.moveDown(1);
    doc.fontSize(8).fillColor("#94a3b8").text(`Generated by B.Ed Institute Portal — ${new Date().toISOString()}`, {
      align: "center",
    });
  });
}

export async function zipAdmissionPack(pdfBuffer) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const archive = archiver("zip", { zlib: { level: 6 } });
    const pass = new PassThrough();
    pass.on("data", (c) => chunks.push(c));
    pass.on("end", () => resolve(Buffer.concat(chunks)));
    pass.on("error", reject);
    archive.on("error", reject);
    archive.pipe(pass);
    archive.append(pdfBuffer, { name: "admission-pack.pdf" });
    archive.append(
      Readable.from(
        `This ZIP contains admission-pack.pdf with letter summary, application details, and fee receipts.\n`
      ),
      { name: "README.txt" }
    );
    archive.finalize();
  });
}
